### ISSUE TITLE
Upgrade not working Moodle 3.11.3+

### ISSUE THREAD

**Issue by dewray** [amandadoughty/moodle-mod_peerwork#1]
In both build 20211003 and the previous build, doing a plugin update for Peer Work in two different sites gives the error below.
Peerwork instances from the previous version still work.

> Upgrading to new version

> mod_peerwork
> Error reading from database
> Debug info: Table 'moodle.mdl_course_modules' doesn't exist
> SELECT cm.instance, cm.groupingid
> FROM mdl_course_modules cm
> INNER JOIN mdl_modules m
> ON m.id = cm.module
> AND m.name = 'peerwork'
> [array (
> )]
> Error code: dmlreadexception

> ×Stack trace:
> line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
> line 1212 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
> line 449 of /mod/peerwork/db/upgrade.php: call to mysqli_native_moodle_database->get_recordset_sql()
> line 877 of /lib/upgradelib.php: call to xmldb_peerwork_upgrade()
> line 576 of /lib/upgradelib.php: call to upgrade_plugins_modules()
> line 1929 of /lib/upgradelib.php: call to upgrade_plugins()
> line 713 of /admin/index.php: call to upgrade_noncore()

**Comment by izendegi** [comment]
Hi, 

We've also experienced this issue, and it's caused by a SQL sentence with the standard prefix hardcoded, this PR fixes it: @ #2

**Comment by amandadoughty** [comment]
Thank you @izendegi
