### ISSUE TITLE
Description html-formatting is cleaned up

### ISSUE THREAD

**Issue by simpasami** [amandadoughty/moodle-mod_peerwork#12]
Only activity, where description field edited by editor. After save no html-formatting in text
![image](https://user-images.githubusercontent.com/117338882/224699899-b36adb7b-b729-4337-9b7b-460cfab95783.png)
![image](https://user-images.githubusercontent.com/117338882/224700078-942ef974-57d8-471c-b98c-b75855e04b20.png)

Browser cache is emptied > no changed

Moodle version Moodle 3.9.19 (Build: 20230116)
Peerwork version 2020120107

**Comment by simpasami** [comment]
![image](https://github.com/amandadoughty/moodle-mod_peerwork/assets/117338882/b01cbb93-5352-426d-834a-5dc01e969a59)
![image](https://github.com/amandadoughty/moodle-mod_peerwork/assets/117338882/07686802-5c8f-4db9-9980-f083a7765b87)
![image](https://github.com/amandadoughty/moodle-mod_peerwork/assets/117338882/b4f1dd0f-8d5c-4070-a12d-268fb38f75ee)

**Comment by simpasami** [comment]
Moodle 3.9.20 (Build: 20230313)
Peer-work: 2020120107

**Comment by amandadoughty** [comment]
Closing issue as support for 3.9 ended
