### ISSUE TITLE
Students can't see their results in Dutch

### ISSUE THREAD

**Issue by learning42** [amandadoughty/moodle-mod_peerwork#17]
In Dutch, students get an error code {Exception- number_format(): Argument #1 ($num) must be of type float, string given} when they try and look at their released results. We have found what causes this. The library used has a comment that localised floats should not be used but that is exactly what is happening. As a result, a float is presented with a comma as decimal separator while the function expects a point.... I've added a screenshot of the code and the patch our IT dept provided for now. Hopefully you can adjust this for a next version.
![image-20231212-133632](https://github.com/amandadoughty/moodle-mod_peerwork/assets/131866311/161484e1-def7-4ee7-9780-289ab4aa72ee)
[peerwork.patch](https://github.com/amandadoughty/moodle-mod_peerwork/files/13674184/peerwork.patch)

**Comment by amandadoughty** [comment]
Thank you for reporting and identifying the bug. Now committed to master branch.
