### ISSUE TITLE
New strings not showing in AMOS

### ISSUE THREAD

**Issue by izendegi** [amandadoughty/moodle-mod_peerwork#3]
Hi,

We've detected that the strings added in the latest version of this plugin aren't showed for translation in AMOS.

We've asked about it [in the AMOS forums](https://lang.moodle.org/mod/forum/discuss.php?d=8320#p9734) and David Mudrak said this:

_In case of mod_peerwork there is a problem in the plugin itself. On the [line 305 in their language pack](https://github.com/amandadoughty/moodle-mod_peerwork/blob/5a4b63e1bde368e25983897d490f3b22660bef44/lang/en/peerwork.php#L305) they have the string concatenation operator which is something the AMOS does not recognise yet. The [plugin contribution checklist page](https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings) has more details on the topic._

**Comment by izendegi** [comment]
I'm not sure, but I think #4  should fix it.

**Comment by amandadoughty** [comment]
Thank you for the fix
