### ISSUE TITLE
Hardcoded?

### ISSUE THREAD

**Issue by dinism** [amandadoughty/moodle-mod_peerwork#6]
I'm a PT-PT translator
I think this is hardcoded to english. Is it possible to translate? Thanks
![imagem](https://user-images.githubusercontent.com/14828021/140518044-e26bec19-0a35-4c8f-aec6-932ad5c91ce0.png)

**Comment by dinism** [comment]
I know it can be fixed as you said. But it will be better a code change by author and release a new version.
To translators (as i am) it will fixed to all.

**Comment by amandadoughty** [comment]
Fixed
