### ISSUE TITLE
Missing submodules

### ISSUE THREAD

**Issue by matthewhilton** [amandadoughty/moodle-mod_peerwork#7]
In branch `MOODLE_39_STABLE` there are references to some calculator subplugins as submodules, but their repositories don't seem to exist anymore - getting 404 when trying to access them:

[rebasedpa @ 5b92ac9](https://github.com/CityUniversityLondon/CUL-peerworkcalculator_rebasedpa/tree/5b92ac9828a780188254f5be4db63a9db4387d9a)

[rebasedpav2 @ ebab90a](https://github.com/CityUniversityLondon/CUL-peerworkcalculator_rebasedpav2/tree/ebab90adbe0a1bd89841f02d8a12abd273fdf26c)

[simplepa @ dd4b148](https://github.com/CityUniversityLondon/CUL-peerworkcalculator_simplepa/tree/dd4b14809004173c411428a86bcffdb2f0b718d8)

[trimmedpa @ 38358c8](https://github.com/CityUniversityLondon/CUL-peerworkcalculator_trimmedpa/tree/38358c8477579e00d42e565cb9c89a6602ea60e3)

I'm guessing they are likely private now? Regardless, they should probably be removed.

**Comment by amandadoughty** [comment]
Thanks. Now removed
